name: run_nuclear_tests
on: [push]

jobs:

  # building several Python versions on ubuntu-latest
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      # checking out the repo for accessing files
      - uses: actions/checkout@v4

      # setting up the Python version for this job
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # installing last published version of nuclear from PyPI
      - name: Install dependencies & latest nuklear
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python -m pip install -r requirements.txt --upgrade nuklear

      # running tests
      - name: Test with pytest
        run: |
          python ./tests/data_runner.py
          pytest ./tests/test_cases.py
