name: Test-Python-package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies & latest nuklear
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -r requirements.txt nuklear
          python -m pip install --upgrade nuklear
      - uses: actions/checkout@v4
      - name: Get directory
        run: ls -R ./*
      - name: Test with pytest
        run: |
          pytest
